version: '3.7'

services:
  fe-app:
    build:
      context: ./example-react-fe
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - keycloak-network
    volumes:
      - ./example-react-fe:/usr/src

  fe-api:
    build:
      context: ./frontend-api
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    networks:
      - keycloak-network

  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    environment:
      - "JAVA_OPTS_APPEND=\"-Dkeycloak.profile.feature.upload_scripts=enabled\""
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_LOGLEVEL=DEBUG
      - DB_VENDOR=mysql
      - DB_ADDR=keycloak-mysql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_PORT=3306
    depends_on:
      - keycloak-mysql
    
  keycloak-mysql:
    image: mysql:5.7
    networks:
      - keycloak-network
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    ports:
      - 3306:3306

  terraform:
    build:
      context: ./terraform
      dockerfile: Dockerfile
    command: "/bin/bash -c ./wait-for-it.sh keycloak:8080 --timeout=30 -- terraform plan -out=tfplan -input=false && terraform apply -input=false tfplan"

networks:
  keycloak-network:
    driver: bridge
    ipam:
      driver: default